In [ ]:
Inspecting a DataFrame
When you get a new DataFrame to work with, the first thing you need to do is explore it and see what it contains.
There are several useful methods and attributes for this.

.head() returns the first few rows (the “head” of the DataFrame).
.info() shows information on each of the columns, such as the data type and number of missing values.
.shape returns the number of rows and columns of the DataFrame.
.describe() calculates a few summary statistics for each column.
homelessness is a DataFrame containing estimates of homelessness in each U.S. state in 2018.
The individual column is the number of homeless individuals not part of a family with children. 
The family_members column is the number of homeless individuals part of a family with children. The state_pop column is the state's total population.

pandas is imported for you.

In [ ]:
Instructions 4/4
25 XP
Print some summary statistics that describe the homelessness DataFrame.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
homelessness=pd.read_csv("homelessness.csv")
homelessness

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588
5,5,Mountain,Colorado,7607.0,3250.0,5691287
6,6,New England,Connecticut,2280.0,1696.0,3571520
7,7,South Atlantic,Delaware,708.0,374.0,965479
8,8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,9,South Atlantic,Florida,21443.0,9587.0,21244317
10,10,South Atlantic,Georgia,6943.0,2556.0,10511131
11,11,Pacific,Hawaii,4131.0,2399.0,1420593
12,12,Mountain,Idaho,1297.0,715.0,1750536
13,13,East North Central,Illinois,6752.0,3891.0,12723071
14,14,East North Central,Indiana,3776.0,1482.0,6695497
15,15,West North Central,Iowa,1711.0,1038.0,3148618
16,16,West North Central,Kansas,1443.0,773.0,2911359
17,17,East South Central,Kentucky,2735.0,953.0,4461153
18,18,West South Central,Louisiana,2540.0,519.0,4659690
19,19,New England,Maine,1450.0,1066.0,1339057
20,20,South Atlantic,Maryland,4914.0,2230.0,6035802
21,21,New England,Massachusetts,6811.0,13257.0,6882635
22,22,East North Central,Michigan,5209.0,3142.0,9984072
23,23,West North Central,Minnesota,3993.0,3250.0,5606249
24,24,East South Central,Mississippi,1024.0,328.0,2981020
25,25,West North Central,Missouri,3776.0,2107.0,6121623
26,26,Mountain,Montana,983.0,422.0,1060665
27,27,West North Central,Nebraska,1745.0,676.0,1925614
28,28,Mountain,Nevada,7058.0,486.0,3027341
29,29,New England,New Hampshire,835.0,615.0,1353465
30,30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
31,31,Mountain,New Mexico,1949.0,602.0,2092741
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351
33,33,South Atlantic,North Carolina,6451.0,2817.0,10381615
34,34,West North Central,North Dakota,467.0,75.0,758080
35,35,East North Central,Ohio,6929.0,3320.0,11676341
36,36,West South Central,Oklahoma,2823.0,1048.0,3940235
37,37,Pacific,Oregon,11139.0,3337.0,4181886
38,38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
39,39,New England,Rhode Island,747.0,354.0,1058287
40,40,South Atlantic,South Carolina,3082.0,851.0,5084156
41,41,West North Central,South Dakota,836.0,323.0,878698
42,42,East South Central,Tennessee,6139.0,1744.0,6771631
43,43,West South Central,Texas,19199.0,6111.0,28628666
44,44,Mountain,Utah,1904.0,972.0,3153550
45,45,New England,Vermont,780.0,511.0,624358
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,47,Pacific,Washington,16424.0,5880.0,7523869
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,50,Mountain,Wyoming,434.0,205.0,577601

In [5]:
# Print the head of the homelessness data
print(homelessness.head())

   Unnamed: 0              region       state  individuals  family_members  \
0           0  East South Central     Alabama       2570.0           864.0
1           1             Pacific      Alaska       1434.0           582.0
2           2            Mountain     Arizona       7259.0          2606.0
3           3  West South Central    Arkansas       2280.0           432.0
4           4             Pacific  California     109008.0         20964.0

   state_pop
0    4887681
1     735139
2    7158024
3    3009733
4   39461588

In [6]:
# Print information about homelessness
print(homelessness.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      51 non-null     int64
 1   region          51 non-null     object
 2   state           51 non-null     object
 3   individuals     51 non-null     float64
 4   family_members  51 non-null     float64
 5   state_pop       51 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 2.5+ KB
None

In [7]:
# Print the shape of homelessness
print(homelessness.shape)

(51, 6)

In [8]:
# Print a description of homelessness
print(homelessness.describe())

       Unnamed: 0    individuals  family_members     state_pop
count   51.000000      51.000000       51.000000  5.100000e+01
mean    25.000000    7225.784314     3504.882353  6.405637e+06
std     14.866069   15991.025083     7805.411811  7.327258e+06
min      0.000000     434.000000       75.000000  5.776010e+05
25%     12.500000    1446.500000      592.000000  1.777414e+06
50%     25.000000    3082.000000     1482.000000  4.461153e+06
75%     37.500000    6781.500000     3196.000000  7.340946e+06
max     50.000000  109008.000000    52070.000000  3.946159e+07

In [ ]:
Parts of a DataFrame
To better understand DataFrame objects, it's useful to know that they consist of three components, stored as attributes:

.values: A two-dimensional NumPy array of values.
.columns: An index of columns: the column names.
.index: An index for the rows: either row numbers or row names.
You can usually think of indexes as a list of strings or numbers, though the pandas Index data type allows for more sophisticated options. 
                                                                                                          (These will be covered later in the course.)

homelessness is available.

Instructions
100 XP
Import pandas using the alias pd.
Print a 2D NumPy array of the values in homelessness.
Print the column names of homelessness.
Print the index of homelessness.

In [9]:
# Print the values of homelessness
print(homelessness.values)

[[0 'East South Central' 'Alabama' 2570.0 864.0 4887681]
 [1 'Pacific' 'Alaska' 1434.0 582.0 735139]
 [2 'Mountain' 'Arizona' 7259.0 2606.0 7158024]
 [3 'West South Central' 'Arkansas' 2280.0 432.0 3009733]
 [4 'Pacific' 'California' 109008.0 20964.0 39461588]
 [5 'Mountain' 'Colorado' 7607.0 3250.0 5691287]
 [6 'New England' 'Connecticut' 2280.0 1696.0 3571520]
 [7 'South Atlantic' 'Delaware' 708.0 374.0 965479]
 [8 'South Atlantic' 'District of Columbia' 3770.0 3134.0 701547]
 [9 'South Atlantic' 'Florida' 21443.0 9587.0 21244317]
 [10 'South Atlantic' 'Georgia' 6943.0 2556.0 10511131]
 [11 'Pacific' 'Hawaii' 4131.0 2399.0 1420593]
 [12 'Mountain' 'Idaho' 1297.0 715.0 1750536]
 [13 'East North Central' 'Illinois' 6752.0 3891.0 12723071]
 [14 'East North Central' 'Indiana' 3776.0 1482.0 6695497]
 [15 'West North Central' 'Iowa' 1711.0 1038.0 3148618]
 [16 'West North Central' 'Kansas' 1443.0 773.0 2911359]
 [17 'East South Central' 'Kentucky' 2735.0 953.0 4461153]
 [18 'West South Central' 'Louisiana' 2540.0 519.0 4659690]
 [19 'New England' 'Maine' 1450.0 1066.0 1339057]
 [20 'South Atlantic' 'Maryland' 4914.0 2230.0 6035802]
 [21 'New England' 'Massachusetts' 6811.0 13257.0 6882635]
 [22 'East North Central' 'Michigan' 5209.0 3142.0 9984072]
 [23 'West North Central' 'Minnesota' 3993.0 3250.0 5606249]
 [24 'East South Central' 'Mississippi' 1024.0 328.0 2981020]
 [25 'West North Central' 'Missouri' 3776.0 2107.0 6121623]
 [26 'Mountain' 'Montana' 983.0 422.0 1060665]
 [27 'West North Central' 'Nebraska' 1745.0 676.0 1925614]
 [28 'Mountain' 'Nevada' 7058.0 486.0 3027341]
 [29 'New England' 'New Hampshire' 835.0 615.0 1353465]
 [30 'Mid-Atlantic' 'New Jersey' 6048.0 3350.0 8886025]
 [31 'Mountain' 'New Mexico' 1949.0 602.0 2092741]
 [32 'Mid-Atlantic' 'New York' 39827.0 52070.0 19530351]
 [33 'South Atlantic' 'North Carolina' 6451.0 2817.0 10381615]
 [34 'West North Central' 'North Dakota' 467.0 75.0 758080]
 [35 'East North Central' 'Ohio' 6929.0 3320.0 11676341]
 [36 'West South Central' 'Oklahoma' 2823.0 1048.0 3940235]
 [37 'Pacific' 'Oregon' 11139.0 3337.0 4181886]
 [38 'Mid-Atlantic' 'Pennsylvania' 8163.0 5349.0 12800922]
 [39 'New England' 'Rhode Island' 747.0 354.0 1058287]
 [40 'South Atlantic' 'South Carolina' 3082.0 851.0 5084156]
 [41 'West North Central' 'South Dakota' 836.0 323.0 878698]
 [42 'East South Central' 'Tennessee' 6139.0 1744.0 6771631]
 [43 'West South Central' 'Texas' 19199.0 6111.0 28628666]
 [44 'Mountain' 'Utah' 1904.0 972.0 3153550]
 [45 'New England' 'Vermont' 780.0 511.0 624358]
 [46 'South Atlantic' 'Virginia' 3928.0 2047.0 8501286]
 [47 'Pacific' 'Washington' 16424.0 5880.0 7523869]
 [48 'South Atlantic' 'West Virginia' 1021.0 222.0 1804291]
 [49 'East North Central' 'Wisconsin' 2740.0 2167.0 5807406]
 [50 'Mountain' 'Wyoming' 434.0 205.0 577601]]

In [10]:
# Print the column index of homelessness
print(homelessness.columns)

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='object')

In [11]:
# Print the row index of homelessness
print(homelessness.index)

RangeIndex(start=0, stop=51, step=1)

In [ ]:
Sorting rows
Finding interesting bits of data in a DataFrame is often easier if you change the order of the rows. 
You can sort the rows by passing a column name to . sort_values().

In cases where rows have the same value (this is common if you sort on a categorical variable),
you may wish to break the ties by sorting on another column. You can sort on multiple columns in this way by passing a list of column names.

Sort on …	Syntax
one column	df.sort_values("breed")
multiple columns	df.sort_values(["breed", "weight_kg"])
By combining .sort_values() with .head(), you can answer questions in the form, "What are the top cases where…?".

homelessness is available and pandas is loaded as pd.

Instructions 3/3
30 XP
Sort homelessness by the number of homeless individuals in the individuals column, from smallest to largest, and save this as homelessness_ind.
Print the head of the sorted DataFrame.
Sort homelessness by the number of homeless family_members in descending order, and save this as homelessness_fam.
Sort homelessness first by region (ascending), and then by number of family members (descending). Save this as homelessness_reg_fam.

In [14]:
# Sort homelessness by individuals
homelessness_ind =homelessness.sort_values("individuals")
# Print the top few rows
#print(homelessness_ind.head())
homelessness_ind.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
50,50,Mountain,Wyoming,434.0,205.0,577601
34,34,West North Central,North Dakota,467.0,75.0,758080
7,7,South Atlantic,Delaware,708.0,374.0,965479
39,39,New England,Rhode Island,747.0,354.0,1058287
45,45,New England,Vermont,780.0,511.0,624358

In [15]:
# Sort homelessness by descending family members
homelessness_fam = homelessness.sort_values("family_members",ascending=False)

homelessness_fam.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351
4,4,Pacific,California,109008.0,20964.0,39461588
21,21,New England,Massachusetts,6811.0,13257.0,6882635
9,9,South Atlantic,Florida,21443.0,9587.0,21244317
43,43,West South Central,Texas,19199.0,6111.0,28628666

In [16]:
# Sort homelessness by region, then descending family members
homelessness_reg_fam = homelessness.sort_values(["region","family_members"],ascending=[True,False])

# Print the top few rows
homelessness_reg_fam.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
13,13,East North Central,Illinois,6752.0,3891.0,12723071
35,35,East North Central,Ohio,6929.0,3320.0,11676341
22,22,East North Central,Michigan,5209.0,3142.0,9984072
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
14,14,East North Central,Indiana,3776.0,1482.0,6695497

In [ ]:
Subsetting columns
When working with data, you may not need all of the variables in your dataset. 
Square brackets ([]) can be used to select only the columns that matter to you in an order that makes sense to you. To select only "col_a" of the DataFrame df, use

df["col_a"]
To select "col_a" and "col_b" of df, use

df[["col_a", "col_b"]]
homelessness is available and pandas is loaded as pd.

Instructions 3/3
30 XP
Create a Series called individuals that contains only the individuals column of homelessness.
Create a DataFrame called state_fam that contains only the state and family_members columns of homelessness, in that order.
3
Create a DataFrame called ind_state that contains the individuals and state columns of homelessness, in that order.

In [17]:
# Select the individuals column
individuals =homelessness["individuals"]

individuals.head()

0      2570.0
1      1434.0
2      7259.0
3      2280.0
4    109008.0
Name: individuals, dtype: float64

In [18]:
# Select the state and family_members columns
state_fam = homelessness[["state","family_members"]]

state_fam.head()

        state  family_members
0     Alabama           864.0
1      Alaska           582.0
2     Arizona          2606.0
3    Arkansas           432.0
4  California         20964.0

In [19]:
# Select only the individuals and state columns, in that order
ind_state = homelessness[["individuals","state"]]

ind_state.head()

   individuals       state
0       2570.0     Alabama
1       1434.0      Alaska
2       7259.0     Arizona
3       2280.0    Arkansas
4     109008.0  California

In [ ]:
Subsetting rows
A large part of data science is about finding which bits of your dataset are interesting. One of the simplest techniques for this is to find a subset of rows that match some criteria. This is sometimes known as filtering rows or selecting rows.

There are many ways to subset a DataFrame, perhaps the most common is to use relational operators to return True or False for each row, then pass that inside square brackets.

dogs[dogs["height_cm"] > 60]
dogs[dogs["color"] == "tan"]
You can filter for multiple conditions at once by using the "bitwise and" operator, &.

dogs[(dogs["height_cm"] > 60) & (dogs["color"] == "tan")]
homelessness is available and pandas is loaded as pd.

Instructions 3/3
30 XP
Filter homelessness for cases where the number of individuals is greater than ten thousand, assigning to ind_gt_10k. View the printed result.

Filter homelessness for cases where the USA Census region is "Mountain", assigning to mountain_reg. View the printed result.

Filter homelessness for cases where the number of family_members is less than one thousand and the region is "Pacific", assigning to fam_lt_1k_pac. View the printed result.

In [20]:
# Filter for rows where individuals is greater than 10000
ind_gt_10k = homelessness[homelessness["individuals"]>10000]

# See the result
ind_gt_10k

,Unnamed: 0,region,state,individuals,family_members,state_pop
4,4,Pacific,California,109008.0,20964.0,39461588
9,9,South Atlantic,Florida,21443.0,9587.0,21244317
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351
37,37,Pacific,Oregon,11139.0,3337.0,4181886
43,43,West South Central,Texas,19199.0,6111.0,28628666
47,47,Pacific,Washington,16424.0,5880.0,7523869

In [21]:
# Filter for rows where region is Mountain
mountain_reg = homelessness[homelessness["region"]=="Mountain"]

# See the result
mountain_reg

    Unnamed: 0    region       state  individuals  family_members  state_pop
2            2  Mountain     Arizona       7259.0          2606.0    7158024
5            5  Mountain    Colorado       7607.0          3250.0    5691287
12          12  Mountain       Idaho       1297.0           715.0    1750536
26          26  Mountain     Montana        983.0           422.0    1060665
28          28  Mountain      Nevada       7058.0           486.0    3027341
31          31  Mountain  New Mexico       1949.0           602.0    2092741
44          44  Mountain        Utah       1904.0           972.0    3153550
50          50  Mountain     Wyoming        434.0           205.0     577601

In [22]:
# Filter for rows where family_members is less than 1000 
# and region is Pacific
fam_lt_1k_pac = homelessness[(homelessness["family_members"]<1000) & (homelessness["region"]=="Pacific")]

# See the result
fam_lt_1k_pac

   Unnamed: 0   region   state  individuals  family_members  state_pop
1           1  Pacific  Alaska       1434.0           582.0     735139

In [ ]:
Subsetting rows by categorical variables
Subsetting data based on a categorical variable often involves using the or operator (|) to select rows from multiple categories. This can get tedious when you want all states in one of three different regions, for example. Instead, use the .isin() method, which will allow you to tackle this problem by writing one condition instead of three separate ones.

colors = ["brown", "black", "tan"]
condition = dogs["color"].isin(colors)
dogs[condition]
homelessness is available and pandas is loaded as pd.

Instructions
100 XP
Filter homelessness for cases where the USA census state is in the list of Mojave states, canu, assigning to mojave_homelessness. View the printed result.

In [23]:
# The Mojave Desert states
canu = ["California", "Arizona", "Nevada", "Utah"]

# Filter for rows in the Mojave Desert states
mojave_homelessness = homelessness[homelessness["state"].isin(canu)]

# See the result
mojave_homelessness

    Unnamed: 0    region       state  individuals  family_members  state_pop
2            2  Mountain     Arizona       7259.0          2606.0    7158024
4            4   Pacific  California     109008.0         20964.0   39461588
28          28  Mountain      Nevada       7058.0           486.0    3027341
44          44  Mountain        Utah       1904.0           972.0    3153550

In [ ]:
You aren't stuck with just the data you are given. Instead, you can add new columns to a DataFrame. This has many names, such as transforming, mutating, and feature engineering.

You can create new columns from scratch, but it is also common to derive them from other columns, for example, by adding columns together or by changing their units.

homelessness is a DataFrame containing estimates of homelessness in each U.S. state in 2018. The individual column is the number of homeless individuals not part of a family with children. The family_members column is the number of homeless individuals part of a family with children. The state_pop column is the state's total population.

homelessness is available and pandas is loaded as pd.

Instructions
100 XP
Add a new column to homelessness, named total, containing the sum of the individuals and family_members columns.
Add another column to homelessness, named p_homeless, containing the proportion of the total homeless population to the total population in each state state_pop.

In [25]:
# Add total col as sum of individuals and family_members
homelessness["total"]=homelessness["individuals"]+homelessness["family_members"]

# Add p_homeless col as proportion of total homeless population to the state population
homelessness["p_homeless"] = homelessness["total"] / homelessness["state_pop"]


# See the result
homelessness.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop,total,p_homeless
0,0,East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.000703
1,1,Pacific,Alaska,1434.0,582.0,735139,2016.0,0.002742
2,2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.001378
3,3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.000901
4,4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.003294

In [ ]:
Combo-attack!
You've seen the four most common types of data manipulation: sorting rows, subsetting columns, subsetting rows, and adding new columns. In a real-life data analysis, you can mix and match these four manipulations to answer a multitude of questions.

In this exercise, you'll answer the question, "Which state has the highest number of homeless individuals per 10,000 people in the state?" Combine your new pandas skills to find out.

Instructions
100 XP
Add a column to homelessness, indiv_per_10k, containing the number of homeless individuals per ten thousand people in each state, using state_pop for state population.
Subset rows where indiv_per_10k is higher than 20, assigning to high_homelessness.
Sort high_homelessness by descending indiv_per_10k, assigning to high_homelessness_srt.
Select only the state and indiv_per_10k columns of high_homelessness_srt and save as result. Look at the result.

In [26]:
# Create indiv_per_10k col as homeless individuals per 10k state pop
homelessness["indiv_per_10k"] = homelessness["individuals"]/homelessness["state_pop"]*10000

homelessness["indiv_per_10k"]

0      5.258117
1     19.506515
2     10.141067
3      7.575423
4     27.623825
5     13.366045
6      6.383837
7      7.333148
8     53.738381
9     10.093523
10     6.605379
11    29.079406
12     7.409159
13     5.306895
14     5.639611
15     5.434130
16     4.956448
17     6.130702
18     5.451006
19    10.828516
20     8.141420
21     9.895919
22     5.217310
23     7.122409
24     3.435066
25     6.168299
26     9.267771
27     9.062045
28    23.314189
29     6.169351
30     6.806193
31     9.313145
32    20.392363
33     6.213869
34     6.160300
35     5.934222
36     7.164547
37    26.636307
38     6.376884
39     7.058577
40     6.061970
41     9.514077
42     9.065763
43     6.706215
44     6.037640
45    12.492833
46     4.620477
47    21.829195
48     5.658732
49     4.718113
50     7.513837
Name: indiv_per_10k, dtype: float64

In [27]:
# Subset rows for indiv_per_10k greater than 20
high_homelessness = homelessness[homelessness["indiv_per_10k"] > 20]
high_homelessness

,Unnamed: 0,region,state,individuals,family_members,state_pop,total,p_homeless,indiv_per_10k
4,4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.003294,27.623825
8,8,South Atlantic,District of Columbia,3770.0,3134.0,701547,6904.0,0.009841,53.738381
11,11,Pacific,Hawaii,4131.0,2399.0,1420593,6530.0,0.004597,29.079406
28,28,Mountain,Nevada,7058.0,486.0,3027341,7544.0,0.002492,23.314189
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351,91897.0,0.004705,20.392363
37,37,Pacific,Oregon,11139.0,3337.0,4181886,14476.0,0.003462,26.636307
47,47,Pacific,Washington,16424.0,5880.0,7523869,22304.0,0.002964,21.829195

In [28]:
# Sort high_homelessness by descending indiv_per_10k
high_homelessness_srt = high_homelessness.sort_values("indiv_per_10k",ascending=False)

high_homelessness_srt

,Unnamed: 0,region,state,individuals,family_members,state_pop,total,p_homeless,indiv_per_10k
8,8,South Atlantic,District of Columbia,3770.0,3134.0,701547,6904.0,0.009841,53.738381
11,11,Pacific,Hawaii,4131.0,2399.0,1420593,6530.0,0.004597,29.079406
4,4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.003294,27.623825
37,37,Pacific,Oregon,11139.0,3337.0,4181886,14476.0,0.003462,26.636307
28,28,Mountain,Nevada,7058.0,486.0,3027341,7544.0,0.002492,23.314189
47,47,Pacific,Washington,16424.0,5880.0,7523869,22304.0,0.002964,21.829195
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351,91897.0,0.004705,20.392363

In [29]:
# From high_homelessness_srt, select the state and indiv_per_10k cols
result = high_homelessness_srt[["state","indiv_per_10k"]]

# See the result
print(result)

                   state  indiv_per_10k
8   District of Columbia      53.738381
11                Hawaii      29.079406
4             California      27.623825
37                Oregon      26.636307
28                Nevada      23.314189
47            Washington      21.829195
32              New York      20.392363